name: Build and Test with CI

on:
  push:
    branches:
      - CI
  pull_request:
    branches:
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [11]
        emulator-api: [29, 30]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Set up Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.emulator-api }}
          arch: x86_64
          distribution: 'emulator-darwin'  # Replace with your distribution

      - name: Build and Test with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assemble
          ./gradlew --stacktrace test
          ./gradlew --stacktrace -Pandroid.testInstrumentationRunnerArguments.notAnnotation=androidx.test.filters.LargeTest connectedAndroidTest
          ./gradlew --stacktrace -Pandroid.testInstrumentationRunnerArguments.annotation=androidx.test.filters.LargeTest connectedPlayDebugAndroidTest

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-artifacts
          path: omniNotes/build/outputs/apk/
